mac:
	g++ -std=c++11 -I/opt/homebrew/opt/openssl/include -L/opt/homebrew/opt/openssl/lib -lssl -lcrypto main.cpp ./chess_api/chesscom_api.cpp
windass:
	g++ -std=c++17 main.cpp ./chess_api/chesscom_api.cpp -lssl -lcrypto
